language: node_js
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
    - "$HOME/.npm"
notifications:
  slack:
      on_success: change
      on_failure: always
node_js:
  - 'node'
  - '7'
  - '6'
os:
  - linux
before_install:
  - npm install -g codecov
  - npm i -g travis-deploy-once
install:
  - npm i -g npm@latest
  - npm ci
before_script:
  - npm prune
  - echo "Check if TypeScript files have valid syntax/types"
  - npm run type-check
after_success:
  - codecov
  - travis-deploy-once && npx -p node@8 npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
